- src/api.js
- src/nep2.js
- src/utils.js
> Standardize code styles

- .gitignore
- lib/index.js
- src/api.js
- src/wallet.js
I exported several functions that were needed to debug the ledger signing.
main change is the split of getAccountsFromPrivateKey into getAccountsFromPrivateKey and getAccountsFromPublicKey as the ledger is not supposed to expose the private key.
> PR to allow Ledger Nano S integration

- .eslintrc.js
- LICENSE
- package-lock.json
- package.json
- src/api.js
- src/index.js
- src/nep2.js
- src/transactions.js
- src/utils.js
- src/wallet.js
- tests/index.js
- webpack.config.js
PR for #16 .
- Use EsLint with StandardJS
- JSDocs style
- Retarget webpack to index.js instead of api.js (use index.js to manage exports)
- Extract transaction logic out as seperate file (wallet.js should manage Account logic)
- ~~Refactor and expand the test suite~~
- Separate test suite into individual files for each js file for unit testing
- use index.js for high level integration testing
- Rename encrypt_wif, decrypt_wif to encryptWIF, decryptWIF
> Keep in line with JS naming convention
- Change getAccountsFromWIFKey, getAccountsFromPrivateKey, getAccountsFromPublicKey to getAccountFromWIFKey, getAccountFromPrivateKey, getAccountFromPublicKey
> Methods now output an Account object instead of encasing them in an array
> Improvement #16

- README.md
- package.json
Standardise `README.md` to fix with CoZ cover page template.
Also correct the license type in `package.json`.
> README update and license fix

- src/api/NeonDB.js
- tests/api/neonDB.js
> Gif txid pls༼つ◕ ◕༽つ

- source/changelog.rst
- source/index.rst
- source/reference/index.rst
- source/reference/utility.rst
- source/rpc/index.rst
- source/smart_contracts/index.rst
- source/utility.rst
- src/utils.js
- Added a changelog page for overview of changes
- Added utils page
- Added utils to reference
> Docs: Changelog + Utils

- README.md
- package.json
- source/readme.md
- src/sc/index.js
- src/wallet/core.js
- tests/api/coinmarketcap.js
- tests/api/neonDB.js
- tests/api/nep5.js
- tests/rpc/index.js
- tests/rpx.js
- tests/sc/index.js
- tests/sc/scriptBuilder.js
- tests/transactions/components.js
- tests/transactions/index.js
- tests/wallet/Account.js
- tests/wallet/core.js
- Add docs link to readme
- Add build scripts for docs
- Add `tests` folder to run and ran lint
- Ran through tests and change imports to import directly from file instead of through Neon. Tests are meant to test business logic, not import logic.
> Cleanup dev

- src/api/NeonDB.js
- tests/api/neonDB.js
> Enable usage on private blockchain

- src/nep2.js
> Add Unicode Normalization Form C to NEP2 implementation

- src/utils.js
- tests/utils.js
> Little endian var ints + tests

- src/utils.js
- tests/utils.js
Notes:
* Renamed fixed82num to fixed8hex2num, kept the original export too but added a depreciation warning
* Same as above for num2fixed8/num2fixed8hex
* Small consistency edits
> Utils unit tests

- source/reference/wallet.rst
- source/wallet.rst
- src/consts.js
- src/wallet/Account.js
- src/wallet/Wallet.js
- src/wallet/index.d.ts
- src/wallet/index.js
- src/wallet/nep2.js
- tests/wallet/Account.js
- tests/wallet/Wallet.js
- tests/wallet/simpleWallet.json
- tests/wallet/testWallet.json
Closes #82 
- Introduces the NEP-6 Wallet class
- readFile/writeFile using fs
- addAccount to add account to wallet
- Improved Account 
- encrypt/decrypt function
- export function
- label, extra property
- Deprecation
- wallet.encryptWifAccount, wallet.generateEncryptedWif, wallet.encryptWIF, wallet.decryptWIF
> [Feature] NEP Wallet

- package.json
- source/api/index.rst
- source/changelog.rst
- source/conf.py
- source/constants.rst
- source/index.rst
- source/installation.rst
- source/overview.rst
- source/reference/wallet.rst
- source/rpc/index.rst
- source/smart_contracts/index.rst
- source/transactions/index.rst
- source/utility.rst
- source/wallet.rst
- src/consts.js
- src/rpc/index.d.ts
- src/utils.d.ts
- src/wallet/Balance.js
- src/wallet/Wallet.js
- src/wallet/index.d.ts
- src/wallet/nep2.js
- test.html
- tests/wallet/Wallet.js
- tests/wallet/nep2.js
clean up docs in prep for v2.2.0 release
> Maintence: Docs cleanup

- README.md
> Added docs build commands to readme

- src/api/nep5.js
- tests/integration/api/nep5.js
- tests/unit/api/mockData.json
> fix(api): NEP5 Token parsing by decimals

- package-lock.json
- package.json
tested with `npm run test:unit` and `npm run lint`
> fix(npm): clean up dependencies

- src/api/core.js
- src/api/neonDB.js
- src/transactions/components.js
- src/transactions/core.js
- src/transactions/index.d.ts
- src/transactions/transaction.js
- src/utils.d.ts
- src/utils.js
- src/wallet/Balance.js
- src/wallet/index.d.ts
- tests/unit/api/core.js
- tests/unit/api/neonDB.js
- tests/unit/api/neoscan.js
- tests/unit/transactions/components.js
- tests/unit/transactions/core.js
- tests/unit/transactions/transaction.js
- tests/unit/utils.js
- tests/unit/wallet/Balance.js
Transit most of the system to using Fixed8 for value storage.
> fix(all): Use Fixed8

- .eslintrc.js
- .gitignore
- package-lock.json
- package.json
- src/api/coinmarketcap.js
- src/api/core.js
- src/api/neonDB.js
- src/api/neoscan.js
- src/api/nep5.js
- src/logging.js
- src/transactions/core.js
- src/wallet/Wallet.js
- src/wallet/nep2.js
- tests/common.js
- tests/integration/api/core.js
- tests/integration/api/nep5.js
- tests/unit/api/coinmarketcap.js
- tests/unit/api/core.js
- Logging through stdout and stderr
- Default logging off
- Relies on logging library `loglevel`
> feat(logs): Logging

- src/sc/ScriptBuilder.js
- src/sc/core.js
- src/sc/index.js
- test/mocha.opts
- test/unit/sc/core.js
- test/unit/sc/data.json
- test/unit/sc/scriptBuilder.js
> feat(sc): createScript to accept multiple scripts

- package-lock.json
- package.json
- src/rpc/client.js
> chore(npm):Upgrade deps to latest

- src/api/coinmarketcap.js
- src/rpc/client.js
- src/rpc/query.js
- src/transactions/transaction.js
- src/wallet/Account.js
- src/wallet/Wallet.js
> fix(all): Add more logging throughout

- src/api/core.js
- src/api/neonDB.js
- test/integration/api/neonDB.js
- test/unit/api/core.js
- test/unit/api/mockData.json
- Core methods to utilise user provided parameters when given.
> fix(api): use user provided parameters when given

- src/wallet/index.js
- src/wallet/message.js
- test/unit/wallet/message.js
What current issue(s) from Github does this address?
https://github.com/CityOfZion/neon-js/issues/167
This PR allows you to sign using private or WIF key and verify message using your public key.
> feat(wallet): Message verification and signing

- src/sc/ScriptBuilder.js
- src/sc/index.d.ts
- src/utils.d.ts
- src/utils.js
- test/unit/sc/data.json
- test/unit/sc/scriptBuilder.js
Closes [#177](https://github.com/CityOfZion/neon-js/issues/177)
> feat(sc): ScriptBuilder.toScriptParams

- docs/guides-basic_invoke.md
- website/i18n/en.json
- website/sidebars.json
> docs(all): add basic doInvoke guide

- docs/guides-adv_invokeconcepts.md
- website/i18n/en.json
- website/sidebars.json
> docs(all): advanced doInvoke

- src/networks.json
> fix(src): fixed faulty url in network config file

- .gitignore
- docs/api-u.md
- docs/guides-adv_multitx.md
- docs/guides-basic-privnet.md
- docs/guides-basic_claimgas.md
- docs/guides-basic_createscript.md
- docs/guides-basic_sendasset.md
Added some util conversion methods + fixed some typo's
> docs(docs): fixed typo's, added util conversion methods

- src/api/core.js
- test/unit/api/core.js
Allows for custom claiming of gas using claimGas
> feat(api): claimGas claims override

- src/sc/ScriptBuilder.js
- test/unit/sc/scriptBuilder.js
> fix(sc):fix scriptBuilder toScriptParams error parsing nonce

- docs/api-wallet.md
- src/index.d.ts
- src/wallet/index.js
- Added scripthash to semantic api
- Set the correct return types
- Modified docs accordingly + fixed typos
> chore(wallet): extended semantic api - modified docs accordingly

- src/api/core.js
- src/api/typings/core.d.ts
- src/consts.d.ts
- src/index.d.ts
- src/transactions/typings/Transaction.d.ts
Fixes #258
I'm new to the codebase so please review if changes are correct.
> TypeScript definitions fix

- src/rpc/typings/Network.d.ts
- src/rpc/typings/Protocol.d.ts
- src/transactions/typings/Transaction.d.ts
- src/wallet/Account.js
- src/wallet/typings/Account.d.ts
- src/wallet/typings/Wallet.d.ts
ran through the constructors and made it possible to new without arguments
> fix(all): Optional arguments for all constructors

- src/api/core.js
Missed out on this previously.
> fix(api): add ability to claim gas from smart contract

- src/api/neonDB.js
- src/api/neoscan.js
- test/unit/api/mockData.json
- test/unit/api/switch.js
> fix(api): Fix getRPCEndpoint not gathering good nodes properly

- docs/guides-basic-privnet.md
- docs/guides-basic_invoke.md
- docs/guides-basic_sendasset.md
Small typo fixes in three separate files, all in docs.
> Typo updates for documentation

- src/wallet/core.js
- src/wallet/message.js
- test/unit/wallet/core.js
Add ability to verify signature of hexstrings.
> feat(wallet): verifySignature

- packages/neon-nep5/README.md
- packages/neon-nep9/README.md
- packages/neon-nep9/__tests__/extract.ts
- packages/neon-nep9/__tests__/parse.ts
- packages/neon-nep9/jest.config.js
- packages/neon-nep9/package.json
- packages/neon-nep9/src/extract.ts
- packages/neon-nep9/src/index.ts
- packages/neon-nep9/src/parse.ts
- packages/neon-nep9/src/plugin.ts
- packages/neon-nep9/tsconfig.json
- tsconfig.json
> feat(neon-nep9): Add NEP9 package

- packages/neon-core/src/tx/transaction/BaseTransaction.ts
> fix(neon-core): Remove applyTx from Balance.calculate

- docs/api/core/settings.md
- docs/api/core/tx.md
- docs/api/plugin/nep5.md
- docs/api/plugin/nep9.md
- docs/changelog/latest.md
- docs/changelog/v3.md
- docs/guides/basic/privnet.md
- packages/neon-nep9/README.md
- Update old code on guides
- Update changelog for v3
- Update changelog for v4
> docs(guide): Update old code on guides

- helpers/urls.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-domain/__integration__/NeoNS.ts
- packages/neon-nep5/__integration__/main.ts
Extracts helper function to pull urls into a separate file. Also improves the algorithm by cutting the list at a random point so we do not hit the same urls forever and using a good enough heuristic of checking the difference in blocks between 2 urls are similar to ensure we have a good enough url.
> fix(test): Fix test helper being hung up on first url

- helpers/urls.ts
- packages/neon-core/__tests__/tx/transaction/IssueTransaction.ts
- packages/neon-core/__tests__/tx/transaction/issueTx.json
- packages/neon-core/src/consts.ts
- packages/neon-core/src/tx/transaction/IssueTransaction.ts
- packages/neon-core/src/tx/transaction/Transaction.ts
- packages/neon-core/src/tx/transaction/index.ts
> feat(core): Implement parsing for issue transaction

- packages/neon-core/__tests__/tx/transaction/EnrollmentTransaction.ts
- packages/neon-core/__tests__/tx/transaction/enrollmentTx.json
- packages/neon-core/src/consts.ts
- packages/neon-core/src/tx/transaction/EnrollmentTransaction.ts
- packages/neon-core/src/tx/transaction/Transaction.ts
- packages/neon-core/src/tx/transaction/index.ts
> feat(core): Implement parsing for enrollment transaction

- packages/neon-core/__tests__/sc/ContractParam.ts
- packages/neon-core/__tests__/u/Fixed8.ts
- packages/neon-core/src/u/Fixed8.ts
> fix(core): Fix decoding of negative Fixed8 hex string

- packages/neon-api/package.json
- packages/neon-core/package.json
- yarn.lock
Updated axios to 0.19.0 to resolve warning for https://www.npmjs.com/advisories/880
> chore(npm): Updated axios dependency

- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__tests__/rpc/Query.ts
- packages/neon-core/__tests__/rpc/RPCClient.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/RPCClient.ts
@snowypowers  this is same as https://github.com/CityOfZion/neon-js/pull/443 only it's merging into `dev` branch.
> Rpc methods of 2.10.2

- CONTRIBUTING.md
- README.md
add line to suggest branching from dev and point PRs to the correct branch.
> docs(readme):Update contributing readme

- packages/neon-core/__tests__/u/Fixed8.ts
- packages/neon-core/src/u/Fixed8.ts
- packages/neon-nep5/__tests__/abi.ts
- packages/neon-nep5/src/abi.ts
> Fix Fixed8 overflow in nep5 transfer method

- packages/neon-api/__integration__/provider/neoCli.ts
use a list of nodes and perform a basic check before commiting to using it for integration tests
> test(neon-api): Fix NeoCli tests

- .circleci/config.yml
- lerna.json
- package.json
- Update CircleCI to have publish steps.
- Update npm scripts to contain all the version and publish commands.
> chore(ci): Add CI release process

- packages/neon-core/__tests__/u/StringStream.ts
- packages/neon-core/src/u/Fixed8.ts
- packages/neon-core/src/u/StringStream.ts
- packages/neon-core/src/u/convert.ts
- packages/neon-core/src/u/hash.ts
- packages/neon-core/src/u/misc.ts
- Add tests for StringStream.readVarInt.
- Add docs for Fixed8 and StringStream.
> chore(u): Clean up docs and types for neon-core/u

- .circleci/config.yml
- helpers/getBaseBranch.js
- packages/neon-core/src/rpc/Protocol.ts
This changes the lint job to lint only changed files but becomes stricter. This means all changed files will have to resolve their lint issues.
> chore(ci): Only lint changed files

- packages/neon-js/src/networks.ts
- Remove CozNet since it does not exist currently in neo3.
- Update MainNet and TestNet to reflect the current status in neo-node repository.
> feat(main): Update networks to match neo3 network list

- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__tests__/sc/ContractParam.ts
- packages/neon-core/__tests__/sc/ScriptBuilder.ts
- packages/neon-core/__tests__/sc/ScriptParser.ts
- packages/neon-core/src/sc/ContractParam.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/ScriptParser.ts
- packages/neon-js/src/index.ts
- ContractParam follows NeonObject model
- Update ScriptBuilder to remove any typing
- Update ScriptParser to remove any typing
- Select the best node for rpc integration tests
> feat(sc): Update sc to be more consistent

- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/RPCClient.ts
- packages/neon-core/src/tx/components/Cosigner.ts
- packages/neon-core/src/tx/components/TransactionAttribute.ts
- packages/neon-core/src/tx/components/Witness.ts
- packages/neon-core/src/tx/transaction/Transaction.ts
- packages/neon-core/src/types.ts
- Add TransactionJson, WitnessJson, CosignerJson interfaces.
- Renamed BlockHeaderLike and BlockLike to BlockHeaderJson and BlockJson.
> feat(tx): Add Json interfaces for blockchain objects

- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/package.json
- tsconfig-base.json
Add engines section to neon-core specifying minimum node version of 10.
> chore(build): Update tsconfig to target node 10

- packages/neon-core/__tests__/u/HexString.ts
- packages/neon-core/__tests__/u/base64.ts
- packages/neon-core/src/u/HexString.ts
- packages/neon-core/src/u/base64.ts
- Rename functions to indicate usage for hex
- Add helper functions in HexString
> fix(u): scope base64 conversion to hex

- docs/api/plugin/api.md
- docs/examples/network.md
- docs/guides/basic/privnet.md
- examples/browser/README.md
- examples/browser/subscribenotifications/demo/demo.css
- examples/browser/subscribenotifications/demo/demo.details
- examples/browser/subscribenotifications/demo/demo.html
- examples/browser/subscribenotifications/demo/demo.js
- packages/neon-api/README.md
Documentation for #514.
Pushing it as a draft PR in order to keep track of it. Feel free to close it if it's better to just open another PR when the interface for #514 is consolidated.
> docs(api): Notification API docs

- packages/neon-api/__integration__/notifications/class.ts
- packages/neon-api/package.json
- packages/neon-api/src/notifications/class.ts
- test.html
- yarn.lock
- Install ws as a dependency
- Add integration smoke test
- Fix small bug where messages could still come in as close does not reject messages in buffer
> fix(api): Add ws for notifications to work in Node

- packages/neon-api/__integration__/notifications/class.ts
- packages/neon-api/package.json
- packages/neon-api/src/notifications/class.ts
- packages/neon-api/src/notifications/subscription.ts
- yarn.lock
- Convert unsubscribe apis that unsubscribes whole contracts to return awaitable Promises
- Update closing logic to include a force terminate after 5s
- Pin dependencies to exact versions
> fix(api): Fix websocket not closing quickly enough

- .circleci/config.yml
- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__tests__/tx/transaction/Transaction.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/core.ts
- packages/neon-core/src/tx/components/Witness.ts
- packages/neon-core/src/tx/transaction/Transaction.ts
- Correctly sign and transmit transaction
- Convert integration tests for RPCClient to rely on localnet
> fix(tx): Get sendRawTransaction working

- packages/neon-api/__tests__/transaction/builder.ts
- packages/neon-core/__tests__/tx/components/Signer.ts
- packages/neon-core/__tests__/tx/components/WitnessScope.ts
- packages/neon-core/__tests__/tx/transaction/Transaction.ts
- packages/neon-core/src/tx/components/Signer.ts
- packages/neon-core/src/tx/components/WitnessScope.ts
- Add FeeOnly to WitnessScope.
- Change default of WitnessScope to FeeOnly.
> feat(tx): Update WitnessScope for preview3

- packages/neon-core/src/sc/ContractParam.ts
Update ContractParamType from preview3. Almost all the integer values used have been changed.
> feat(sc): Update ContractParamType for preview3

- packages/neon-api/src/transaction/validator.ts
- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__tests__/rpc/RPCClient.ts
- packages/neon-core/src/consts.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/RPCClient.ts
- packages/neon-core/src/rpc/parse.ts
- packages/neon-core/src/tx/components/Signer.ts
- Update contract hashes for neo and gas
- Update json field names to lowercase without underscores
- Merge RPCVMResponse as InvokeResult
- Add new field tx to InvokeResult (unclear what it is for now)
- Change WitnessHashes to Signers in invokefunction and invokescript
consensus_data -> consensusdata
tcp_port -> tcpport
ws_port -> wsport
user_agent -> useragent
> feat(rpc): Update RPC for preview3

- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__tests__/tx/transaction/Transaction.json
- packages/neon-core/__tests__/tx/transaction/Transaction.ts
- packages/neon-core/src/consts.ts
- packages/neon-core/src/tx/transaction/Transaction.ts
- Fix headerSize of transaction now that sender is not serialized
- Activate test for getStorage
- Fill data for Transaction serialization/deserialization test
> test(core): Fix more tests for preview3

- docs/changelog/latest.md
- docs/guides/basic/transfer.md
- examples/basic/transfer.js
- helpers/generateContractHash.js
- packages/neon-core/src/consts.ts
- packages/neon-core/src/sc/InteropServiceCode.ts
- Update guide to work for preview3
- Update Policy contract hash
- Write preview3 changelog
> chore(changelog): Update changelog for preview3

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- Adds devcontainer for easy setup of a dev env complete with solonet attached
- Adds launch.json for debugging with jest within vscode
> chore(dev): Add devcontainer

- packages/neon-core/__tests__/sc/OpToken.ts
- packages/neon-core/__tests__/testWallet.json
- packages/neon-core/__tests__/wallet/Wallet.ts
- packages/neon-core/__tests__/wallet/multisig.ts
- packages/neon-core/src/sc/OpToken.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- packages/neon-core/src/wallet/multisig.ts
Using OpTokens, I can now break down the script into opcodes and its params. This PR uses the OpTokens to fix the multi sig methods that have been broken so far.
> fix(wallet): Fix multi signature methods in wallet

- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
- packages/neon-core/__integration__/rpc/clients/Nep5TrackerRpcClient.ts
- packages/neon-core/__integration__/wallet/multisig.ts
- packages/neon-core/src/sc/OpToken.ts
- packages/neon-core/src/tx/components/Witness.ts
- packages/neon-core/src/wallet/Account.ts
- packages/neon-core/src/wallet/multisig.ts
Adds an integration test for sending with multisig account.
- Fix tx.Witness.buildMultiSig
- Fix wallet.getSignaturesFromInvocationScript
> Add integration test for sending with multisig account

- packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
- packages/neon-core/__tests__/rpc/RPCClient.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
fix https://github.com/CityOfZion/neon-js/issues/593
> feat(rpc): add getunclaimedgas RPC method

- packages/neon-core/__tests__/u/misc.ts
- packages/neon-core/src/u/misc.ts
Recreation of https://github.com/CityOfZion/neon-js/pull/603 to enable circleci
> feat(u): Add getSerializedSize

- packages/neon-core/__tests__/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/types.ts
Add emitContractCall to replace emitAppCall. Also add the deprecated tag to emitAppCall.
> feat(sc): ScriptBuilder.emitContractCall

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
Minor fix to use latest container and also apt-get update to ensure dependencies can be found.
> chore(dev): Update Docker devcontainer

- packages/neon-core/src/u/base64.ts
- packages/neon-js/src/experimental/contract.ts
- packages/neon-js/src/experimental/helpers.ts
- packages/neon-js/src/experimental/index.ts
- packages/neon-js/src/experimental/nep5/base.ts
- packages/neon-js/src/experimental/types.ts
- Add conversion methods between utf8 and base64 (I should rename all the old ascii methods to utf8)
- Rework imports to point correctly to package instead of the lib folder.
- Move typings out of index.ts file so we do not have circular deps (works but bad practice)
> refactor(experimental): Reshuffle imports

- packages/neon-api/__tests__/transaction/validator.ts
- packages/neon-api/src/transaction/validator.ts
- Port integration tests to unit tests
- Rework each validation to return the suggestion instead of the full validation result
> refactor(api): Refactor TransactionValidator

- packages/neon-api/package.json
- packages/neon-js/package.json
- packages/neon-ledger/package.json
- yarn.lock
Upgrade Typescript to receive a bug fix. Also updates all other easy to update dev dependencies.
> chore(npm): Update devdependencies

- packages/neon-core/__tests__/tx/components/Signer.ts
- packages/neon-core/src/tx/components/Signer.ts
Properly implement a merge function that merges 2 signers together. 
- Deduplicates customGroups and customContracts.
- If scope is global, merge will wipe all custom data and return a simpler signer.
- Also updates add methods to skip when scope is global.
> feat(tx): Signer.merge

- jest.config.js
> chore(test): Update ts-jest config prop

- packages/neon-api/__integration__/NetworkFacade.ts
- packages/neon-api/src/NetworkFacade.ts
- packages/neon-api/src/plugin.ts
- packages/neon-api/src/transaction/TransactionBuilder.ts
- packages/neon-api/src/transaction/index.ts
- packages/neon-api/src/transaction/signing.ts
- packages/neon-api/src/transaction/validator.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/contracts/Nep17Contract.ts
- packages/neon-core/src/tx/transaction/Transaction.ts
- packages/neon-core/src/wallet/core.ts
NetworkFacade is the new high level API interface replacing the old methods of doInvoke,sendAsset and claimGas. It is intended to be a quick way to perform common wallet operations as well as a note to developers on how to use the SDK.
> feat(api): NetworkFacade

- packages/neon-api/__integration__/transaction/validator.ts
- packages/neon-api/src/transaction/validator.ts
- packages/neon-core/src/sc/OpToken.ts
- packages/neon-core/src/sc/fees.ts
- packages/neon-core/src/u/BigInteger.ts
Fix up old tests for TransactionValidator
> test(api): Fix up integration tests for TransactionValidator

- docs/changelog/latest.md
- docs/guides/basic/facade.md
- examples/basic/facade.js
- website/core/Footer.js
- website/i18n/en.json
- website/sidebars.json
- website/siteConfig.js
Add a guide for NetworkFacade and update package to point to `next` distribution.
> docs(guides): Add facade guide

- packages/neon-core/src/sc/ScriptBuilder.ts
- packages/neon-core/src/wallet/Account.ts
- tsconfig-base.json
- tsconfig-test.json
- Remove node10 workaround in ScriptBuilder
- Add skipLibCheck and forceConsistentCasingInFileNames to tsconfig
- Inherit test tsconfig from base config
- Remove util dependency from Account
> chore(all): Reduce nodejs imports

- packages/neon-api/src/NetworkFacade.ts
- packages/neon-api/src/transaction/TransactionBuilder.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- Breakout verification and signing logic as public methods in NetworkFacade
- Allow appending of hex scripts in TransactionBuilder
> feat(api): Increase flexibility in NetworkFacade & TransactionBuilder

- packages/neon-api/__integration__/NetworkFacade.ts
- packages/neon-api/src/NetworkFacade.ts
- packages/neon-api/src/transaction/TransactionBuilder.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/clients/ApplicationLogsRpcClient.ts
- testHelpers.ts
Convenience method for claiming gas in NetworkFacade.
> feat(api): NetworkFacade.claimGas

- packages/neon-api/__integration__/provider/dora.ts
- packages/neon-api/src/plugin.ts
- packages/neon-api/src/provider/dora/class.ts
- packages/neon-api/src/provider/dora/core.ts
- packages/neon-api/src/provider/dora/index.ts
- packages/neon-api/src/provider/dora/responses.ts
- packages/neon-api/src/provider/neoCli/core.ts
- packages/neon-api/src/provider/neoCli/transform.ts
Most of the logic is similar to neoCli so some refactor to reuse the methods.
#700
> feat(api): Add dora API support

- packages/neon-api/__integration__/NetworkFacade.ts
- packages/neon-api/src/NetworkFacade.ts
- packages/neon-api/src/api/getCandidates.ts
- packages/neon-api/src/transaction/TransactionBuilder.ts
- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
- packages/neon-core/__integration__/sc/contracts/NeoContract.ts
- packages/neon-core/src/sc/contracts/NeoContract.ts
- packages/neon-core/src/sc/contracts/templates/NeoTemplateAbi.json
- packages/neon-core/src/types.ts
Add voting functionality to NetworkFacade.
- TransactionBuilder.addVote to add the logic to a transaction
- GetCandidates method to pull the list of eligible candidates
- NetworkFacade.vote for the high level API
> feat(api): Voting functionality

- docs/changelog/v5.md
Late changelog update to follow the changes published in next.10
> docs(changelog): Update changelog for v5.0.0-next.10

- .circleci/config.yml
Prevent publish steps from running on non-tagged commits.
> fix(ci): Fix publish flow runs

- packages/neon-core/src/consts.ts
- packages/neon-js/src/networks.ts
Updates the testnet magic numbers to reflect those used in the current testnet.
> update magic numbers to reflect ecosystem

- packages/neon-api/src/transaction/validator.ts
https://github.com/CityOfZion/neon-js/issues/760
> feature: fix nep17 tx validation

- packages/neon-api/README.md
- packages/neon-api/src/index.ts
- packages/neon-api/src/plugin.ts
- packages/neon-js/README.md
- packages/neon-js/src/index.ts
- packages/neon-ledger/README.md
- packages/neon-ledger/src/index.ts
- packages/neon-ledger/src/plugin.ts
- packages/neon-ledger/test.node.js
- packages/neon-nep9/README.md
- packages/neon-nep9/src/index.ts
- packages/neon-nep9/src/plugin.ts
Got rid of settings so there is no need for state in the packages anymore.
> feat(all): Remove plugin style system

- common/api/neon-core.api.json
- common/api/neon-core.api.md
- packages/neon-core/src/consts.ts
Updating magic number constants for N3 to be aligned with https://github.com/neo-project/neo-node/releases/tag/v3.0.2
> feat(const): update magic number constants for N3

- packages/neon-api/src/NetworkFacade.ts
- packages/neon-api/src/transaction/signing.ts
> feat(api): Change signingCallback signature

- common/api/neon-core.api.json
- common/api/neon-core.api.md
- packages/neon-core/__tests__/wallet/verify.ts
- packages/neon-core/src/wallet/verify.ts
- yarn.lock
Add an optional arg to isAddress that allows users to specify a specific address version to match. If provided, the function will return false if the version does not match.
Resolve #797
> feat(wallet): Add arg to isAddress to verify version

- packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
- packages/neon-core/__tests__/rpc/Query.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
> feat(rpc): calculateNetworkFee

- packages/neon-core/__tests__/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/ContractParam.ts
> Identify Any/null as valid contract param.

- docs/changelog/v5.md
> chore(docs): update changelog v5.0.0-next.11 -> v5.0.0-next.17

- README.md
close #823
part of #826
- Update author/maintainer to snowy
- Update sample code to N3
- Fix hyper links
Note I change the import style from `require()` to `import` because that is also what is used in he guides. I tried to keep it consistent.
> chore(docs): update readme for N3

- packages/neon-core/src/sc/InteropServicePrices.ts
following https://github.com/neo-project/neo/pull/2749
> fix(sc): Remove GetRandom from fixed interop price list

- docs/changelog/v5.md
- packages/neon-js/src/experimental/helpers.ts
- packages/neon-js/src/experimental/types.ts
> fix(experimental): Apply prioritisation fee

- docs/changelog/v5.md
- packages/neon-api/src/api/calculateNetworkFee.ts
- packages/neon-js/__integration__/experimental/helpers.ts
- packages/neon-js/src/experimental/helpers.ts
> feat(api): smartCalculateNetworkFee

- docs/changelog/v5.md
- packages/neon-core/src/consts.ts
fix https://github.com/CityOfZion/neon-js/issues/871
> fix(const): Fix testnet magic for T5

- docs/changelog/v5.md
- packages/neon-core/__tests__/tx/components/WitnessCondition.ts
- packages/neon-core/src/tx/components/WitnessCondition.ts
fixes https://github.com/CityOfZion/neon-js/issues/876
> fix(tx): WitnessCondition serialization & toJson fixes

- docs/changelog/v5.md
- packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
- packages/neon-core/__tests__/rpc/Query.ts
- packages/neon-core/src/rpc/Query.ts
- packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
- packages/neon-core/src/rpc/parse.ts
- packages/neon-core/src/sc/StackItem.ts
Raul is the author, I only sent the PR with the correct commit name and correct branch location.
> feat: add traverseiterator utility methods to Query.ts and NeoServerRpcClient.ts

- docs/changelog/v5.md
> fix(docs): fix version from patch to minor

- .circleci/config.yml
- .devcontainer/docker-compose.yml
- packages/neon-core/__integration__/rpc/RPCClient.ts
- packages/neon-core/__tests__/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/OpCode.ts
- packages/neon-core/src/sc/OpCodeAnnotations.ts
- packages/neon-core/src/sc/OpCodePrices.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
- testHelpers.ts
Also resolves some issue with Node17+ and localhost for testing
> feat(sc): Add PUSHT and PUSHF opcodes

- docs/changelog/v5.md
to include changes of #890 before creating a release
> chore(docs): update changelog

- README.md
If you look at the readme right now you will notice some strange codes on the beginning. This PR simply fix this
> docs: Fix header images/link on README.md

- docs/changelog/v5.md
- packages/neon-core/__tests__/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
>  fix(sc): support emitting Maps in ScriptBuilder

- docs/changelog/v5.md
- packages/neon-core/__tests__/sc/ScriptBuilder.ts
- packages/neon-core/src/sc/ScriptBuilder.ts
> fix(sc): fix incorrect handling of numbers in ScriptBuilder

- README.md
This Pull Request includes links to NeonDappkit and WalletConnectSDK. These are significant repositories for COZ and the Neo community. Highlighting them is crucial to enhance the understanding and facilitate the development of Dapps.
> docs: Add links to NeonDappkit and WcSdk on NeonJs README.md

- .circleci/config.yml
- package-lock.json
- package.json
- packages/neon-core/package.json
- packages/neon-ledger/README.md
- packages/neon-ledger/package.json
- packages/neon-ledger/src/ErrorCode.ts
- tsconfig-base.json
- Upgrade typescript and various other packages.
- Replaced a lodash method with native method supported since node v17
- Update node testing versions to use v20.
> chore(npm): Upgrade code dependencies
