src/sc/scriptBuilder.js, src/utils.js, tests/sc/scriptBuilder.js
_emitNum was returning invalid results i.e 500 would return 1f4 whereas the bytecode should be f401
* _emitNum() reversed order of hex bytes and ensured leading 0 added to msb (when applicable)
* added unit tests for -1, 0, 13, 500, 65536
* utils.js: hex2bytes() convert a hex string to an array and optionally reverse order
* utils.js:  int2hex() convert an integer to hex and add leading zeros
=> bugfix to _emitNum w/unit tests

package.json, webpack.config.js
- Adds Uglify+production status to build. Reduces filesize to 500kb from 1.5mb
- Adds browser support. Building for browser will allow this package to be used more easily in front end packages instead of just Node.
=> Webpack: Uglify + Browser

src/transactions/components.js
Verified in the Neo source: https://git.io/vFWYR
=> serializeWitness should use varint script lengths

source/index.rst, source/interface.rst, source/transactions/index.rst, src/rpc/query.js, src/sc/index.js
Resolves #68
This PR adds a `interface` page describing the interface that external APi needs to take in order to support the information required by `neon-js` to do its work.
=> Api standard

src/rpc/client.js
This PR contains only the source code change, and not the build files.
=> Correct Query.getBlock reference in RPCClient

src/api/coinmarketcap.js
If the price of GAS is 18.21 the current implementation will return 18. This fixes that. It also adds USD as a normal currency simplifying a condition.
=> Don't truncate prices to integers

src/api/core.js, src/transactions/transaction.js, src/wallet/Balance.js, tests/api/core.js, tests/api/nep5.js, tests/transactions/transaction.js, tests/wallet/Balance.js
Closes #83 
- Bugfix Balance constructor reading wrong object for assets.
- Transaction construction now alters the state of the provided Balance.
- ``api.core.sendTx`` now alters the state of the provided Balance (config.balance).
=> [Fix] Transactions spend coins from Balance

src/api/nep5.js
the `stack[0].value` returns ‘’ when using an address with no balance
causing it to throw “fixed8hex must be hex” in `fixed82num()`.
=> catch getTokenBalance error when using an address with no balance

src/sc/ScriptBuilder.js, src/transactions/components.js, src/utils.js, tests/unit/utils.js
=> Using byte lengths instead of hexstring lengths

src/utils.js, tests/integration/api/nep5.js, tests/unit/api/mockData.json, tests/unit/api/nep5.js, tests/unit/utils.js
Resolves #105 
- `fixed82num` now returns 0 when receiving empty string
- Add tests for `getToken` for zero balance
- Add a integration test for `getToken` to ensure data consistency
=> [Fix] Fixed82num not accepting empty string as zero

.circleci/config.yml
- Upgrade CI Image to Node 8.9.3 (includes latest security fix)
- Do a version check at the start
=> [CI] Update CI image to latest Node LTS

debug/tokenBalance.js, package.json, src/api/nep5.js, tests/integration/api/core.js, tests/integration/api/nep5.js
- Fix transferTokens test
- Clean up integration tests, all to use testKeys instead of strings
- `doInvoke neoscan` is now a token transfer test
- use package.json to whitelist files for publishing
=> [Fix] Fix transferToken tests

src/api/core.js, src/api/index.d.ts, tests/integration/api/core.js
An API switch variable that allows toggling between neonDB and neoscan.
This allows us to load balance and ensure we don't keep hitting an endpoint when its down.
Methods:
`api.core.setApiSwitch`: set the apiSwitch to a predetermined number. 0 for 100% neoscan, 1 for 100% neonDB.
`api.core.setSwitchFreeze`: set the switch to freeze or not. Frozen switch will not dynamically react to failing endpoints.
=> feat(api): Api switch to toggle between neonDB and neoscan

src/transactions/core.js, src/transactions/transaction.js, tests/integration/api/core.js, tests/unit/transactions/transaction.js
- Implement a simple check for privateKey before signing. Encountered case where WIF was inserted instead and resulted in wrong signature.
- Expanded `Transaction.sign` to accept `Account` and `WIF`
- write tests for `Transaction.sign`
=> fix(tx): core.signTransaction to check for privateKey

src/transactions/exclusive.js
This fixes the setting of default values for the invocation script.  Without this, the default values can be overridden by `null` or `undefined` if the key is not set on the transaction config, which I don't believe is the intention.
=> Fixed default values for invocation exclusive config

src/api/core.js
This updates the params comments to properly nest some keys under the `config` object that they belong to.  Without this, it makes it look like these are separate function arguments when they are not.
=> Fixed params comments to nest config arguments

package-lock.json, package.json, src/utils.js, tests/unit/utils.js
This introduces the `Fixed8` util class extending `bignumber.js`. Basically I pinned on several methods for parsing hexstrings since it is used so often within `neon-js`.
we want to move towards using this safer number types for storing value and this class would allow us to calculate and transform data safely and easily.
=> feat(util): Fixed8 class based off bignumber

src/api/neonDB.js, src/api/neoscan.js, src/transactions/transaction.js, src/utils.js, src/wallet/Claims.js, src/wallet/index.js, tests/unit/transactions/createData.json, tests/unit/transactions/transaction.js
- `claimGas` to fully use Fixed8
- Changed how we parse neoscan and neonDB input to return Fixed8 numbers
- created a `Claims` class in `wallet` as a simple way to make a native `Claims` object with a Claims-like JS object.
- Updated Fixed8 to use `round` instead of `trunc`. `round` should be safer for numbers that are already affected by JS floating point issue.
=> feat(tx): Claims using Fixed8 

src/api/coinmarketcap.js, src/api/core.js, src/api/index.d.ts, src/api/neonDB.js, src/api/neoscan.js, src/sc/index.d.ts, src/transactions/index.d.ts, src/transactions/transaction.js, src/utils.d.ts, src/utils.js, src/wallet/Account.js, src/wallet/Balance.js, src/wallet/Claims.js, src/wallet/Wallet.js, src/wallet/components.js, src/wallet/index.d.ts, src/wallet/index.js, tests/unit/api/neonDB.js, tests/unit/api/neoscan.js, tests/unit/wallet/Claims.js, tests/unit/wallet/components.js
With the introduction of Fixed8, it becomes increasingly more difficult to use `neon-js` because there are too many native classes required. For example, many things will fail if we just merely pass in a JS object of a similar structure due to the nature of Fixed8.
This PR addresses the issue by:
- Having constructors for the relevant objects take in the JS objects of the accepted shape and spitting out the native `neon-js` equivalent. (`Balance`, `Claims`)
- Having helper methods for constructing the smaller components that are not promoted to its own class (eg. `Coin`, `AssetBalance`)
- There are some experimentation with customizing the printing of objects to aid debugging. These are implementation with the `util.inspect.custom` symbol.
- Clean up typings and docstrings.
- Unexport …
=> feat(all): JS Object constructors

docs/tutorial/basic-sendasset.rst, src/api/core.js, test/unit/api/core.js
Solves https://github.com/CityOfZion/neon-js/issues/147
This PR allows you to send assets from a contract. It supports Contract and Invocation transactions (which are used in neo-boa examples such as https://github.com/CityOfZion/neo-boa/blob/master/boa/tests/src/WithdrawTest.py#L100).
I saw very similar functionality for mintTokens. I'm unsure how mintTokens was being used in this case. If we need it to work as before, is there a way to test it? It will be easy to add back in the exact same way as before if needed.
For my implementation I set `invocationScript` to '00' * number of contract parameters which is what the mintTokens version was doing. I did not append the main script's `invocationScript` as the issue says as this does not seem to be needed. The original mintToken …
=> feat(api): Support sending assets from contract

src/api/core.js, src/api/index.d.ts, src/rpc/client.js, src/sc/ScriptBuilder.js
All of the core typings were returning `apiConfig`, but in their actual implementation, they were actually returning promises, with various subsequent return types. Updated to reflect accurate return types.
Upon running lint in compliance with the contribution guidelines, it seems there were some existing lint errors. Added those fixes as well.
=> Fix(api): Update core typings

src/api/core.js, src/api/index.d.ts, test/integration/api/core.js, test/integration/rpc/query.js, test/unit/api/core.js
`fillKeys`: By attaching an `Account` to `config.account`, this will fill up the corresponding fields `address`, `publicKey`, `privateKey` using the Account provided.
`fillBalance`: Allows us to attach a previously used balance instead of relying always on an API call for a fresh balance.
=> feat(api): Implement fillKeys and fillBalance

src/sc/ScriptBuilder.js
Take the following for example:
```
const props = {
scriptHash: 'CONTRACT_HASH',
operation: 'do_stuff',
args: [
{ "type": "String", "value": '' },
{ "type": "Integer", "value": 0 }
],
}
const script = Neon.sc.createScript(props)
```
Supplied intents meant to be valid but are blocked by `_emitParam` due to its validation check.
I've create a separate private method `_isValidValue()` that will allow us to expand on this logic in the future if needed while keeping `_emitParam()` readable.
=> Update param.value validation logic to accept 0 and empty string

src/index.d.ts
Couple of API methods are declared with incorrect response type, causing transpiler error when building in TypeScript.
=> Fix API response declarations

src/api/index.d.ts
api.fillUrl was missing from the typing, so it's currently showing as not existing on the exported api object.
=> Fix(api): Add missing typing for api.fillUrl

src/api/neoscan.js
NOTE: This PR's into `dev`, but let me know if I should change it to `master`.
This fixes a bug for addresses that don't exist according to neoscan.  For example, a call to https://api.neoscan.io/api/main_net/v1/get_claimable/fake-address returns:
This causes neon-js to call `new Fixed8(undefined)`, which throws an error:
This is only an issue with neoscan; neonDB returns 0 for invalid addresses such as https://testnet-api.neonwallet.com/v2/address/claims/fake-address.
=> Fixed neoscan.getMaxClaimAmount for invalid addresses

src/sc/ContractParam.js, test/unit/sc/ContractParam.js
neon-js currently does not properly handle sending tokens with decimal sizes other than 8. For example, when sending 1 RHT (a zero-decimal token), neon-js assumes a fixed8 size and converts the number "1" to "100000000" when creating the byte array to add to the contract invocation script. The current workaround for wallets using neon-js is for the user to send 0.00000001 RHT for every 1 RHT intended, a less-than-ideal situation
This fix adds a decimal argument to the byteArray function (this argument is already passed to the function by the latest neon-wallet versions) and pre-divides the value according to the number of decimals before it is passed to num2fixed8 at the end of the function, the end result being a byte array with the correct integer value in fixed8 format.
This fix also …
=> handle decimal sizes other than 8 when converting to ByteArray

src/settings.js, src/transactions/core.js, src/transactions/index.d.ts, src/transactions/index.js, src/transactions/strategy.js, src/transactions/transaction.js, src/transactions/typings/strategy.d.ts, test/unit/transactions/strategy.js, test/unit/transactions/transaction.js
Closes [#208](https://github.com/CityOfZion/neon-js/issues/208)
- Introduces 3 strategies: smallestFirst, biggestFirst and balancedApproach.
- Default strategy is now balancedApproach
- setting is now available to set global strategy.
=> feat(tx): Calculation strategies

src/api/neoscan.js, test/unit/api/mockData.json
This updates the `getMaxClaimAmount` function for the neoscan API to use the preferred v1/get_unclaimed endpoint.
=> Updated neoscan getMaxClaimAmount to use get_unclaimed endpoint

src/api/neonDB.js, src/api/neoscan.js
This is a primitive implementation of a cache so that we don't spam every node for a getBlockCount.
For the call `getRPCEndpoint`, it will still continue to request for a list of best nodes. However, upon compiling the list of best nodes, if the previous best node address is found within the list, it will only ping check the cached node.
=> fix(api): cache rpc endpoint for getRPCEndpoint

src/api/core.js, src/transactions/core.js, src/transactions/transaction.js, test/integration/api/core.js
Added a new `fees` param for calculating transactions. This allows for fees to be attached to transactions.
```
// using API managed methods
config = {
...
fees = 0.00001
}
doInvoke(config).then(...)
// or using direct tx
new Transaction().calculate(balance, strategy, fees)
```
How it works is that you just send GAS to the void. This means that the sum of inputs > sum of outputs for GAS. The excess is considered as fees to the network. First, system fees will be deducted from this excess amount. The current system fees is zero for all transactions so there is no deductions. The remaining amount is considered as network fees and will be used to prioritise transaction picking when it comes to block forming.
This PR also disables the neonDB tests because the testnet neonDB endpoint has …
=> feat(tx): Attachable fees for transactions

src/api/core.js
When debugging locally for adding transaction fee functionality to `neon-wallet` I noticed fees were not being dumped as part of the error handling pattern. This PR adds that info.
=> updates error handling api/core.js

src/sc/core.js
Fellows, it seems that return code for Void (ff) is not passed as `ff`, but as `ff00`, because it is its biginteger representation (see: https://github.com/neo-project/neo/pull/253). For regular types <= 16, it continues the same, a single hex, because it is the same as bigint representation.
=> just reminding void return is ff00

src/rpc/client.js
I was trying to use this method, however it throwed an error because `this.execute` expects a query instance to be passed. (it got a reference)
=> fix(sc): Fix getValidators method

src/wallet/Balance.js, test/unit/wallet/Balance.js
This fixes an issue where calling `balance.confirm()` doesn't update the balance in the same sense that `balance.applyTx(tx, true)` does.
I'm not sure if you're taking fixes for the v3 branch, so if not, please let me know.
=> chore(wallet): fixed balance calculation when marking as confirmed

src/transactions/transaction.js, test/unit/transactions/transaction.js, test/unit/wallet/Balance.js
This fixes an issue I discovered with transactions being double-applied to balances for "contract" and "invocation" transactions.  When using `api.sendAsset` or `api.doInvoke`, the `balance.applyTx` function was effectively being called twice:
**For sendAsset:**
1. via `createTx` → `createContractTx` → `Transaction.calculate` → `Balance.applyTx`
2. via `sendTx` → `applyTx`
**For doInvoke:**
1. via `createTx` → `createInvocationTx` → `Transaction.calculate` → `Balance.applyTx`
2. via `sendTx` → `applyTx`
This removes the call for `Balance.applyTx` from `Transaction.calculate`, leaving it as part of the core api flow.
=> chore(balance): prevent applyTx from being called twice for contracts & invocations

src/wallet/Balance.js
This fixes an issue with the calculations from [my previous PR](https://github.com/CityOfZion/neon-js/pull/324).  I discovered the calculation issue as a result of working on a fix for #329.
In summary, I was initially subtracting `spent` to get the right balance, but that was only necessary because `unconfirmed` had duplicate coins due to `Balance.applyTx` being called twice in my use case.
=> chore(balance): fix balance confirm() calculation

packages/neon-api/__integration__/funcs/main.ts, packages/neon-api/__tests__/func/fill.ts, packages/neon-api/src/funcs/fill.ts
`claimGas` was not checking if the claims was empty, resulting in the rpc node rejecting with a invalid format message. This adds the check to `fillClaims` so that we can exit early with a better message.
=> fix(neon-api): Add check for empty claims in fillClaims

src/rpc/client.js
update RPCClient getVersion to be able to parse neopython's version and the new version string.
=> fix(rpc): fix getVersion parsing

packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/src/rpc/RPCClient.ts
getVersion wasn't properly handling version responses. 
I dropped the regex and went with a string split approach instead. 
I tested against test net and it is reporting versions properly.
=> Chore(rpc client): fix getVersion 

src/transactions/typings/components.d.ts
Possible fix for #350. Im unable to reproduce properly but this is something I noticed that could fix it. I found that the old Account was actually referencing the Account interface from node.
=> fix(typing): Fix typing for buildMultiSig

package-lock.json, package.json, src/sc/ScriptBuilder.js, test/unit/sc/scriptBuilder.js
Port fix over to v3
C# BigInteger uses two's complement which wasn't reflected by the parseInt of javascript. This solution brings in Igor's csbiginteger package which is a javascript implementation of the c# BigInteger class. With this, we should be able to convert correctly. It's a good place to start testing the package out too.
=> fix(sc): Fix ContractParam.Integer transformation

docs/api/plugin/domain.md, docs/changelog/latest.md, docs/changelog/v3.md, packages/neon-domain/README.md, packages/neon-domain/package.json, packages/neon-domain/src/provider/NeoNS/class.ts, packages/neon-domain/src/provider/NeoNS/core.ts, packages/neon-domain/src/provider/common.ts, website/sidebars.json, yarn.lock
- Add simple page for neon-domain
- Add example for neon-domain readme
- Update release notes for v4 and v3
=> docs(neon-domain): Update docs for release

packages/neon-nep5/__integration__/main.ts, packages/neon-nep5/src/main.ts, packages/neon-nep5/src/plugin.ts, packages/neon-nep9/src/parse.ts
You're able to get multiple token balances in 1 call, but not the ability to get multiple tokens (with more detailed info) in 1 call.
This PR resolves this issue, with the addition of `getTokens`
=> feat(neon-nep5): added getTokens functionality

docs/installation.md
'neon-js' is illegal as a variable name in JavaScript because dashes ('-') are not allowed in variable names. This results in an error when executing the script.
This PR fixes the variable name by replacing the dash with an underscore.
=> Fix variable name

packages/neon-core/src/wallet/nep2.ts
https://github.com/CityOfZion/neon-wallet/issues/1661
This PR fixes the punctuation in the error message coming from nep2.ts.
=> feature: fixes issues with nep2 error message verbage

package.json, packages/neon-api/__integration__/funcs/main.ts, packages/neon-api/__tests__/func/fill.ts, packages/neon-api/package.json, packages/neon-core/package.json, packages/neon-core/test.html, packages/neon-core/webpack.config.js, packages/neon-domain/package.json, packages/neon-js/package.json, packages/neon-js/webpack.config.js, packages/neon-nep5/package.json, packages/neon-nep9/package.json, tsconfig-base.json, tsconfig-test.json, webpack.common.js, yarn.lock
- Move webpack to top level dev dep
- Correct `module` exports for all packages
- tsc now defaults to es6/esm on build
=> refactor(webpack): Fix exports for webpack based packages

packages/neon-api/src/index.ts
Fix the mistake where we were trying to override an import. ES6 imports are immutable.
=> fix(api): Fix es6 getter error

.gitignore
New file generated by tsc upgrade. Used for faster builds and therefore can be ignored.
=> chore(git): ignore tsbuildinfo

README.md, packages/neon-api/__integration__/provider/neoscan-testnet.ts, packages/neon-api/__integration__/provider/neoscan.ts, packages/neon-api/__tests__/provider/neoscan/core.ts, packages/neon-api/src/index.ts, packages/neon-api/src/provider/neoscan/class.ts, packages/neon-api/src/provider/neoscan/core.ts, packages/neon-core/src/settings.ts, packages/neon-js/src/index.ts
This is an integration test and a code change to address the following issue:
https://github.com/CityOfZion/neon-js/issues/401
=> Chore: Make Neoscan getRPCEndpoint Respect httpsOnly Flag

docs/guides/basic/createscript.md, packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/src/rpc/parse.ts
With the new update to v2.10.2, the new VM cuts out the word `BREAK`. This PR addresses the change by relaxing the tests assertions to just `HALT` or `FAULT` instead of looking for the exact phrase `HALT, BREAK` or `FAULT, BREAK`.
=> fix(rpc): Update VM status output for neo v2.10.2

packages/neon-core/__tests__/wallet/Wallet.ts, packages/neon-core/src/wallet/Wallet.ts
We have to update the test data when transferring to the neo3 because NEP2 uses a hash of the address and the address in neo3 has changed due to the change in scripthash.
- Update wallet tests to use async await style
- Update wallet json in test
- wallet encrypt decrypt to throw instead of returning Promise.reject. This was causing jest not to catch the errors due to double wrapped promises.
=> fix(wallet): Fix wallet tests and error handling

packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/src/rpc/Query.ts
- Instead of rejecting with string, reject with Error.
- Update code to use throw with async syntax
=> fix(rpc): RpcClient to reject promise with Error

packages/neon-api/__tests__/transaction/builder.ts, packages/neon-api/__tests__/transaction/signer.ts, packages/neon-api/src/transaction/signer.ts, packages/neon-api/src/transaction/util.ts, packages/neon-api/src/transaction/validator.ts, packages/neon-core/__tests__/tx/components/Cosigner.ts, packages/neon-core/__tests__/tx/components/TransactionAttribute.ts, packages/neon-core/__tests__/tx/components/Witness.ts, packages/neon-core/__tests__/tx/transaction/Transaction.ts, packages/neon-core/src/tx/components/Cosigner.ts, packages/neon-core/src/tx/components/TransactionAttribute.ts, packages/neon-core/src/tx/components/Witness.ts, packages/neon-core/src/tx/transaction/Transaction.ts, packages/neon-core/src/u/HexString.ts
This replaces the hexstring fields in the tx folder to use HexString class in u. This should allow more checking and easier development on our side. It also gives us easy 0x stripping, hex checks and removes endian knowledge.
One downside is that it is slightly more messy to write tests. Just like the Fixed8 construct, the string is hidden and we have to keep calling equal or toBigEndian to test the inner values.
=> feat(tx): Use HexString class in tx

.circleci/config.yml, test.sh
- Fix test xml not being uploaded to circleci.
- Add escape for grep when no files found for lint.
=> chore(ci): Fix commands for lint and test

packages/neon-core/package.json, yarn.lock
This PR upgrades the `elliptic` package to it's latest version.
=> chore(npm): Upgrade elliptic to v6.5.2

packages/neon-core/__tests__/sc/ScriptBuilder.ts, packages/neon-core/src/sc/ScriptBuilder.ts, packages/neon-nep5/__tests__/abi.ts, packages/neon-nep5/src/abi.ts, packages/neon-nep5/src/main.ts
fixes #502
Originally, the call to emitAppCall without any arguments will produce a script that will push a `00` at the start of the script. This can be seen as an error if the contract did not consume the parameter, leaving it in the stack.
By adding a check for undefined, we can prevent the `00` from appearing when no arguments are provided. This breaks existing behaviour for all scripts that rely on no arguments filling in an empty parameter. For example, standard NEP5 contracts will consume 2 variables off the stack. This fix will cause the old code to emit only a single variable and result in a fault when running the script.
This can be fixed by explicitly providing an empty array for args (which is what should happen anyway) which will prompt the ScriptBuilder to inject the …
=> fix(sc): Fix emitAppCall with only scriptHash

packages/neon-core/__tests__/wallet/nep2.ts, packages/neon-core/src/wallet/index.ts, packages/neon-core/src/wallet/nep2.ts, packages/neon-core/src/wallet/upgrade.ts, packages/neon-nep5/src/main.ts
Add methods to allow conversion of neo2 wallet data to neo3 wallet. This only works with simple private key based accounts.
=> feat(wallet): Transition method for wallet from neo2 to neo3

package.json, website/package.json, website/yarn.lock, yarn.lock
Using `resolutions` in `package.json` I have manually addressed numerous npm dependency security issues. To test, checkout this branch and run `yarn audit` in either the website or main directories.
=> fix(chore):Fixes all major security vulnerabilities with npm deps

packages/neon-core/src/rpc/RPCClient.ts
timeout was not supposed to be sent as headers but passed as configuration to axios.
=> fix(rpc): Move timeout out of headers in RPCClient

.eslintrc.js, tslint.json
- Remove camelcase rule since many interfaces coming from c# code are using camelcase.
- Remove redundant tslint file.
=> chore(lint): Remove camelcase rule

packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/RPCClient.ts
- optional verbose parameter now accepts booleans.
- remove getBlockSysFee.
- amend getVersion to read the keys correctly.
- update test data to use new neo3 chain.
=> feat(rpc): Update RPC to 3.0.0-preview2-00

packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/RPCClient.ts
BREAKING CHANGE
- invokeFunction RPC call does not support ...params anymore as we need a new parameter afterwards.
- Add new checkedWitnessHashes param for invokeFunction and invokeScript.
The RPCs accept an extra parameter which is an array of witnesses that we have signatures for. This allows us to run scripts with successful witness checks and return us accurate gas consumption values.
=> feat(rpc): Update invoke RPCs to accept witness hashes

packages/neon-core/__tests__/u/Fixed8.ts, packages/neon-core/src/u/Fixed8.ts
NEO RPCs sometimes return GAS values as raw numbers like "1000000000" which are sometimes too big to fit within the Fixed8 constrain (Not technical limitations but we would like to make sure every Fixed8 is within the max and min). To resolve this, the `fromRawNumber` method is a way for us to construct Fixed8 from such large raw values.
=> feat(u): Fixed8.fromRawNumber

packages/neon-api/__tests__/transaction/builder.ts, packages/neon-api/src/transaction/builder.ts, packages/neon-api/src/transaction/signer.ts, packages/neon-core/__tests__/tx/components/Signer.ts, packages/neon-core/__tests__/tx/transaction/Transaction.json, packages/neon-core/__tests__/tx/transaction/Transaction.ts, packages/neon-core/src/tx/components/Signer.ts, packages/neon-core/src/tx/components/index.ts, packages/neon-core/src/tx/transaction/Transaction.ts, packages/neon-core/src/tx/transaction/main.ts
Update Cosigner to Signer.
- sender field is now generated from the first Signer.
- Remove sender field from TransactionLike.
- Order of serialization changed. Signer now comes before Attributes.
- Disable some tests as we will need to regenerate them later after changes to interop codes.
=> feat(tx): Update Cosigner to Signer

packages/neon-core/__tests__/rpc/parse.ts, packages/neon-core/__tests__/sc/StackItem.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/parse.ts, packages/neon-core/src/sc/StackItem.ts
- Add StackItemJson to reflect the outputs when running invokefunction or invokescript.
- Removed deserializing of StackItem for now since it is difficult to obtain any test cases to ensure the correctness of the implementation.
=> feat(sc): Update StackItem for preview3

helpers/urls.ts, packages/neon-api/__integration__/funcs/main.ts, packages/neon-api/__integration__/provider/neoscan-testnet.ts
- Use neo-cli provider instead of neoscan
- Disable testnet neoscan tests since its broken
=> fix(tests): Use neocli node as provider for integration tests

docs/structure.md, packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/__integration__/rpc/clients/Nep5TrackerRpcClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/RPCClient.ts, packages/neon-core/src/rpc/clients/ApplicationLogsRpcClient.ts, packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/src/rpc/clients/Nep5TrackerRpcClient.ts, packages/neon-core/src/rpc/clients/RpcDispatcher.ts, packages/neon-core/src/rpc/clients/index.ts, packages/neon-core/src/rpc/index.ts, testHelpers.ts
Utilizing the mixin pattern, I am able to break out the RPC API into separate interfaces.
- RpcDispatcher now contains the core logic for sending out the rpc payload.
- Add support for NEP5Tracker and ApplicationLog RPC calls.
- Moved implementation from RPCClient to NeoServerRpcClient.
- RPCClient old functionality is retained for now. Added the new supported calls.
- We are still missing wallet methods but this is intentional. I do not expect much benefits for the normal consumer.
=> feat(rpc): Add plugin methods

website/pages/en/index.js
As a first time `neon-js` user I'm going through the website and wanted to "get started". The link originally points to the "installation" page which is actually the 2nd page of the "Get Started" section. The first would be the `overview` page, which I actually found to contain useful information. 
This PR changes the link to point to the first page of the get started section.
=> chore(docs): Change get started link to overview

packages/neon-core/__tests__/sc/OpToken.ts, packages/neon-core/src/sc/OpToken.ts, packages/neon-core/src/sc/index.ts
OpToken is a tokenized form of a script. This is generated from parsing a VM script and breaking it down into tokens and its params if any. The core motivation here is to have a better system that the current ScriptParser in order to correctly breakdown the multisig account script.
=> feat(sc): OpToken

packages/neon-core/__tests__/wallet/Account.ts, packages/neon-core/src/wallet/Account.ts, packages/neon-core/src/wallet/core.ts
Update public key extraction for Account to attempt to pull the public key from the verification script before falling back to private key. This should allow more flexibility without requiring private key decryption.
- Add getVerificationScriptFromPublicKey method.
- Update publicKey getter to check verification script first.
- Update scriptHash getter to convert verification script to hex first.
=> fix(wallet): Generate public key from verification script

packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/__tests__/sc/ContractParam.ts, packages/neon-core/__tests__/sc/ScriptBuilder.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/sc/ContractParam.ts, packages/neon-core/src/sc/ScriptBuilder.ts
- Fix ContractParam not exiting upon seeing Hash160
- Fix Query.invokeFunction not exporting inputs correctly.
- Adjust emitHexString to choose endianness on seeing type.
=> fix(sc): Fix emitHexString emitting wrong endian

helpers/urls.ts, packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/__tests__/rpc/clients/RpcDispatcher.ts, packages/neon-core/src/rpc/clients/RpcDispatcher.ts
Guard against scheme-less urls as axios does not handle them well on server side.
A simple string match will do for us. We currently only operate on http/https protocol so we can just ensure all urls start with it.
Fixes #587
=> fix(rpc): Guard against non-http urls

packages/neon-core/__tests__/internal.ts, packages/neon-core/__tests__/sc/ContractParam.ts, packages/neon-core/__tests__/sc/ScriptBuilder.ts, packages/neon-core/src/sc/ContractParam.ts, packages/neon-core/src/sc/ScriptBuilder.ts, packages/neon-domain/src/provider/NeoNS/core.ts, packages/neon-js/src/index.ts
Rework how ContractParam construction works. Introduce fromJson and restructure the methods to have clear separation of logic. Static methods are now the preferred entry points with fromJson being the common entrypoint.
- Introduce ContractParamJson which is the direct json output coming from c#.
- Reduce constructor to type validation.
- Move parsing and transformation logic into static methods.
- Add fromJson method as a main entrypoint from external systems.
- Rework ContractParamLike to be a union of the class and json format.
- Add tests for parseEnum.
=> feat(sc): Improve ContractParam with fromJson

.circleci/config.yml, packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
This container contains the latest pull as of 1 November 2020 which is close to preview4. This PR disables all failing tests but does not attempt to fix it.
=> chore(ci): Update integration container to use v3.0.0-head

packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
Rename getValidators to getNextBlockValidators on RpcClient. Data has not changed.
=> fix(rpc): Rename getValidators to getNextBlockValidators

packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
getVersion now returns the magic which is important to sign transactions. Instead of parsing and returning the useragent, this changes the method to return the full json response without any edits.
=> feat(rpc): Update getVersion to return full version json

packages/neon-core/__integration__/sc/contracts/Nep5Contract.ts, packages/neon-core/__tests__/sc/contracts/BaseContract.ts, packages/neon-core/__tests__/sc/contracts/Nep5Contract.ts, packages/neon-core/__tests__/testWallet.json, packages/neon-core/src/consts.ts, packages/neon-core/src/sc/contracts/BaseContract.ts, packages/neon-core/src/sc/contracts/Nep5Contract.ts, packages/neon-core/src/sc/contracts/Nep5TemplateMethods.json, packages/neon-core/src/sc/contracts/index.ts, packages/neon-core/src/sc/index.ts, packages/neon-core/src/sc/types.ts, packages/neon-core/tsconfig.json
A SmartContract framework for simple contract script construction. 
Before, the old framework revolves around the interface `ScriptIntent` (which is very similar to the new `ContractCall` interface). This was designed to be a simple object that SDK users can create to denote a smart contract method call. However, it was not really fully supported by the old `neon-nep5` package, which was coupled tightly with the ScriptBuilder. The `args` field was also `unknown`, leading to multiple parsing issues as there was insufficient information to verify and serialize the data.
This PR reworks `ScriptIntent` and the `neon-nep5` package for better support:
`ScriptIntent` is now superceded by `ContractCall`. With NEO3 standardizing the entry point, we can now support the (scriptHash, operation, args) …
=> feat(sc): A SmartContract base class

packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/src/rpc/Query.ts
invokeFunction and invokeScript now returns the script as a base64 string and returns a new `exception` field. We do not post process the fields at the moment so this is a simple type update.
=> fix(rpc): Update invokeFunction and invokeScript

packages/neon-core/__tests__/u/BigInteger.ts, packages/neon-core/src/u/BigInteger.ts
In order to transit from Fixed8, the SDK will need to be able to parse decimal numbers. The new `BigInteger` class does not support decimals correctly. This introduces methods on BigInteger to work with decimals numbers. It effectively transforms the decimal numbers into a BigInteger by shifting the decimal place.
=> feat(u): BigInteger.fromDecimal

packages/neon-core/__tests__/rpc/RPCClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
Use fromJson method instead of constructor. The constructor was expecting `safeMethods` but fromJson takes `safemethods`. 
Closes #618
=> fix(rpc): Fix getContractState RPC call converting manifest wrongly

packages/neon-core/src/sc/ScriptBuilder.ts
udpate ScriptBuilder.ts: value equals to false should be treated as a valid value.
=> fix(sc): Add false as a valid value for ContractParam.value

docs/api/plugin/api.md, docs/changelog/latest.md, docs/examples/network.md, examples/browser/subscribenotifications/demo/demo.js, lerna.json, packages/neon-api/src/notifications/class.ts, packages/neon-core/package.json, packages/neon-js/package.json, packages/neon-js/src/networks.ts, packages/neon-ledger/package.json, packages/neon-nep5/package.json, packages/neon-nep9/package.json
Following the discussion on #624, this PR removes the notification server urls that are used by default when the network is set to either "MainNet" or "TestNet", reverting some of the changes applied in #514 and #515.
After this PR is merged I'll make an announcement to the broader community and, after a grace period, shut down the servers.
=> fix(api): Remove default notification urls

packages/neon-core/__tests__/sc/OpToken.ts, packages/neon-core/__tests__/u/HexString.ts, packages/neon-core/src/sc/OpToken.ts, packages/neon-core/src/u/HexString.ts
Converts an OpToken back to hexstring format.
Also adjusts HexString.fromNumber as the little endian option did not make sense. num2hexstring needs a size so just use toString to get the hex directly.
=> feat(sc): OpToken.toScript

packages/neon-core/__tests__/sc/OpToken.ts, packages/neon-core/src/sc/OpToken.ts
Converts an integer into an OpToken to push a number onto the stack. Pushing a number is harder than usual due to the required logic to read and understand the cheapest OpCode to use.
=> feat(sc): OpToken.forInteger

helpers/urls.ts
Attempt to fix the flaky integration tests. Removes all old failing urls and also add a timeout to fail fast.
=> fix(test): Add timeout for url test helper

packages/neon-api/__tests__/transaction/validator.ts, packages/neon-api/src/transaction/validator.ts, packages/neon-core/src/tx/transaction/Transaction.ts
- Update the max lifespan to 24 hrs with 15s blocks.
- Update validator recommendation to 1hr with 15s blocks.
- Update validator warning to appear only when the transaction has lifespan less than 5 mins.
=> feat(tx): Update MAX_TRANSACTION_LIFESPAN for preview4

helpers/generateContractHash.js, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/src/consts.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/clients/NeoServerRpcClient.ts
- Add getcommittee and invokecontractverify methods
- Update native contract hashes to match the ones in preview4
- Rearrange NeoServerRpcClient methods for better lookup
- Add tx field back to InvokeResult. This only appears when a wallet is open on the RPC server side.
=> feat(rpc): Update RPC methods to match preview4

packages/neon-core/src/sc/ScriptBuilder.ts, packages/neon-core/typings/node.d.ts
Original import was using nodejs util. Fix by adding a typing reference to global so that it will reference window.TextEncoder in browser & global.TextEncoder in node.
Simple test case:
```
var sb = new Neon.sc.ScriptBuilder();
sb.emitString("sasas");
```
=> fix(sc): Import TextEncoder correctly

packages/neon-core/__tests__/sc/ScriptBuilder.ts, packages/neon-core/src/sc/ScriptBuilder.ts, packages/neon-js/src/experimental/helpers.ts
Fix emission of string type ContractParam. There was double encoding instead of single.
=> fix(sc): Fix ContractParam.string emission

.circleci/config.yml, packages/neon-core/package.json
Updates target engines to Node12 and above. With Node10 ending LTS on 30 Apr, there is little reason to stick to Node10 when NEO3 release timeline is likely to be similar.
=> chore(npm): Target Node12 & above

packages/neon-api/package.json, packages/neon-js/package.json, packages/neon-js/src/index.ts, packages/neon-js/test.html, packages/neon-ledger/package.json, packages/neon-nep9/package.json, packages/neon-test/package.json, packages/neon-test/src/index.ts, packages/neon-test/tsconfig.json, tsconfig-base.json, webpack.common.js
Fix neon-js typings being incorrect. Webpack was producing incorrect typings.
- Disable type emission from webpack. Use tsc typings directly instead.
- Emit es6 modules in lib/ and allow webpack to do the conversion to commonjs.
- Add neon-test package as a playground for manual testing.
- Also fix peer dependencies being incorrect.
=> fix(typings): Fix neon-js typings

package.json, packages/neon-core/package.json, packages/neon-core/typings/node.d.ts, tsconfig-base.json, yarn.lock
Remove skipLibCheck from base tsconfig. This enforces lib checks for all files.
- Re-add bignumber.js as dependency (deprecated but not removed at the moment)
- Add @tapable workaround for webpack typings
- Remove old @types/nodes workaround for TextEncoder
=> fix(typings): Remove skipLibCheck

.vscode/launch.json
Makes vscode debugging easier by not jumping into promise implementations.
=> chore: Skip node builtins during debugging

packages/neon-api/src/transaction/validator.ts
Potentially fix #714. The docker container does not have any token contracts on it so I cannot test this out but my suspicion is on us not correctly calling the invoke functions.
=> fix(api): Pass in signers when validating SystemFee

.circleci/config.yml
Refactor workflows to be branch based. This makes it easier to visualise what is happening.
- Renamed workflow build_and_test to pull_request. This will now run on every pull branch.
- Renamed workflow publish to main_flow. This will run on every commit on master/next branch. The publish steps are triggered only when a version tag accompanies the commit.
- Refactor executors to be parameterized to make it easier to transit between node versions.
=> chore(ci): Refactor workflows to be branchbased

packages/neon-core/__tests__/testWallet1.json, packages/neon-core/__tests__/testWallet2.json, packages/neon-core/__tests__/testWallet3.json, packages/neon-core/__tests__/wallet/Account.ts, packages/neon-core/src/wallet/Account.ts, packages/neon-core/src/wallet/Wallet.ts
Close https://github.com/CityOfZion/neon-js/issues/736
The property was initially renamed to `isdefault` by https://github.com/neo-project/neo/pull/1736 now renamed back to `isDefault` by https://github.com/neo-project/neo/pull/2451
=> fix(wallet): Rename account.isdefault to isDefault

website/src/pages/index.js
COZ redirects the frontpage to `dojo.coz.io/neo3/neon-js`. Docusaurus expects the page to be `/neo3/neon-js/`. As such, the relative link `./docs` produces the url `dojo.coz.io/neo3/docs` (Expected link is `dojo.coz.io/neo3/neon-js/docs/`.
Instead of using raw relative links, I have updated the code to import the baseUrl from config and produce a relative link from the domain.
Fix #737
=> docs: Use baseUrl to contruct relative link

packages/neon-core/__tests__/u/random.ts, packages/neon-core/package.json, packages/neon-core/src/u/basic/random.ts, packages/neon-core/typings/secure-random.d.ts
Instead of `secure-random` package, rely on purely `crypto-js` to generate random bytes. Underneath the hood, both attempts to use the native crypto package in browser/node so it should work the same, the only difference being the code that checks the environment to retrieve the correct dependency. 
Possibly fix #752
=> fix(u): rely on crypto-js for random bytes

packages/neon-core/__tests__/sc/manifest/ContractManifest.ts, packages/neon-core/src/sc/manifest/ContractManifest.ts, packages/neon-core/src/sc/manifest/ContractPermission.ts
ContractPermissionDescriptor uses the UIint classes which maintains the 0x prefix when exporting to JSON. It is possible for the C# code to perform a safe parse using TryParse but currently, it uses a string length check to determine the data type. Thus, a non-prefixed string  fails the length check and errors out. This fixes the export to JSON to maintain the prefix for contract hashes.
Fix #756
=> fix(sc): Fix ContractPermissions toJson dropping 0x

.circleci/config.yml, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts
Updates integration test container to use rc3 container. Also removes assertion of object sizes as invokes can return up to 6 fields (tx field is populated when wallet is open on the node).
=> test: Update integration container to rc3

common/api/neon-core.api.json, common/api/neon-core.api.md, packages/neon-api/src/transaction/signing.ts, packages/neon-core/__tests__/tx/transaction/Transaction.ts, packages/neon-core/__tests__/wallet/Account.ts, packages/neon-core/__tests__/wallet/core.ts, packages/neon-core/src/consts.ts, packages/neon-core/src/tx/transaction/Transaction.ts, packages/neon-core/src/wallet/Account.ts, packages/neon-core/src/wallet/core.ts, packages/neon-core/src/wallet/nep2.ts, packages/neon-core/src/wallet/verify.ts
Breakout address version as a configurable parameter.
For now, the classes will default to N3 MainNet's number but classes responsible for address construction are now able to take a parameter indicating the custom version.
- Add new export DEFAULT_ADDRESS_VERSION as the library's default. Old const ADDR_VERSION is now marked deprecated.
- Add additional parameter to Account's constructor and getAddressFromScriptHash method.
- Due to this change, TransactionJson cannot do a serialization roundtrip due to the lack of information. 
Fix #765
=> feat(core): Breakout address version

packages/neon-api/__tests__/transaction/TransactionBuilder.ts, packages/neon-api/src/transaction/TransactionBuilder.ts, packages/neon-core/__tests__/tx/transaction/Transaction.ts, packages/neon-core/src/tx/transaction/Transaction.ts
Reworks sorting so that the Transaction object does not sort by scripthash but instead follows the order of Signers. In N3, the Signers are used as the point of reference while in legacy N2, the signatures are sorted by their scripthash alphabetical order.
- Remove sorting in TransactionBuilder. The Transaction object will do the sort.
- Add some convenience methods to the builder class for directly adding a default signer + witness.
- Update sort in Transaction to sort by Signer instead of scripthash alphabetical order.
Fix #780
=> fix(tx): Fix Transaction sorting of Witness

.circleci/config.yml, packages/neon-api/src/NetworkFacade.ts, packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/__integration__/rpc/clients/NeoServerRpcClient.ts, packages/neon-core/src/rpc/Query.ts, testHelpers.ts
Neo 3.0.3 introduced a breaking change to the getversion RPC method. The network value was moved one level down under protocol, which broke the Facade api in neon-js.
=> fix(rpc): update getversion for Neo3.0.3

packages/neon-core/__integration__/rpc/clients/TokenTrackerRpcClient.ts, packages/neon-core/src/rpc/Query.ts, packages/neon-core/src/rpc/RPCClient.ts, packages/neon-core/src/rpc/clients/TokenTrackerRpcClient.ts, packages/neon-core/src/rpc/clients/index.ts
- Add getNep11Balances, getNep11Transfers, getNep11Properties.
- Rename Nep17Tracker to TokenTracker in line with the rename in neo-modules.
- No proper tests due to the lack of NEP11 contract in the test container at the moment.
=> feat(rpc): Update Nep17Tracker to TokenTracker

common/api/neon-api.api.json, common/api/neon-api.api.md, common/api/neon-core.api.json, common/api/neon-core.api.md, common/api/neon-js.api.json, common/api/neon-js.api.md, packages/neon-api/__integration__/transaction/validator.ts, packages/neon-api/src/api/calculateNetworkFee.ts, packages/neon-api/src/transaction/validator.ts
- Deprecate api.calculateNetworkFee
- Update TransactionValidator to use RPC call to calculate network fee instead
- Update tests to pass in correctly constructed transactions
- Fix #789
=> feat(api): Use RPC call calculateNetworkFee

packages/neon-core/__tests__/rpc/Query.ts, packages/neon-core/package.json, packages/neon-core/src/rpc/Query.ts, yarn.lock
Update the Query type to conform to JSONRPC specs to allow structure values under params. This means either an array or object.
Closes #805.
=> fix(rpc): Tweak Query to conform to jsonrpc params

common/api/neon-core.api.json, common/api/neon-core.api.md, packages/neon-core/__integration__/rpc/RPCClient.ts, packages/neon-core/src/rpc/BatchQuery.ts, packages/neon-core/src/rpc/clients/RpcDispatcher.ts, packages/neon-core/src/rpc/index.ts
BatchQuery allows for an array of jsonrpc calls to be sent over a single rpc call instead of trying to join them together. The batching mechanism is designed with the type system so that the return values are correctly typed. However, this means that the system is forced to throw when any error occurs.
If your request has a danger of failing, use the `sendQueryList` method directly as it does not handle the typing or response unwrapping.
- Add BatchQuery
- Add RpcDispatcher.executeAll and sendQueryList methods
=> feat(rpc): BatchQuery

docs/overview.md, docs/structure.md
close #824 
part of #826
I tested the code in the guides and that all looks fine. That leaves the small edits in this PR. Note that `settings` was removed with #755 
Since I've always been fighting the import system the old code might still be valid, but not with what I'm seeing locally which is why I updated the code snippet in `overview.md`
=> chore(docs): fix code samples/docs

.circleci/config.yml, yarn.lock
Update the default env to Node14 since v12 is EOL in ~1 month. This does not remove v12 support but merely defaults all our CI env to Node14. Tests will still run on Node12.
Fix #827
=> chore(ci): Update default to Node14

packages/neon-core/src/rpc/Query.ts
Reported by Discord user @vzin777
the `state` field of notifications are StackItems not Contract parameters.
=> fix(rpc): fix wrong type for ApplicationLogJson

README.md, docs/installation.md
closes #850 as per https://github.com/CityOfZion/neon-js/issues/850#issuecomment-1221930903
supersedes #868
=> fix(docs): add import note

docs/api/core/const.md, docs/api/core/logging.md, docs/api/core/rpc.md, docs/api/core/sc.md, docs/api/core/tx.md, docs/api/core/wallet.md, docs/changelog/v5.md
Yesterday somebody pointed out that the core docs where not completely up to date either. I updated all of them except for the `tx.md` one (more on this later). The goal was to make all samples and text valid again. I updated wallet addresses and transaction id, hashes and such to point valid Neo3 values
As for `tx.md` I'm not sure what would be valuable content. The majority of it now describes the different transactions we had in Neo2. Stuff like this are no longer a thing
```
Neon.create.claimTx(...args);
```
The only functions we could describe are `addWitness`, `addSigner` and maybe `(de)serialize`. `addAttribute` exists but is obsolete NEO2 stuff.
=> fix(docs): update core docs

docs/changelog/v5.md, packages/neon-core/__tests__/tx/components/WitnessCondition.ts, packages/neon-core/src/tx/components/WitnessCondition.ts, packages/neon-core/src/tx/components/WitnessRule.ts
fixes https://github.com/CityOfZion/neon-js/issues/872
* `WitnessRule` deserialization failed because the type had to be converted to int first
* `BooleanAndCondition` deserialization failed because `!!"00"` evaluated to `true` not `false`.
* `AndCondition` deserialization failed because `this` was undefined when called here
https://github.com/CityOfZion/neon-js/blob/7eb101aa22d92df1bf50a0e0b7e43b2c43f0ecd6/packages/neon-core/src/tx/components/WitnessCondition.ts#L95
=> fix(tx): fix WitnessRule and WitnessCondition deserialization

docs/changelog/v5.md, packages/neon-core/__tests__/u/basic/hex.ts, packages/neon-core/__tests__/wallet/Account.ts, packages/neon-core/__tests__/wallet/verify.ts, packages/neon-core/src/u/basic/hex.ts, packages/neon-core/src/wallet/Account.ts, packages/neon-core/src/wallet/verify.ts
This PR is important to avoid problems when passing 0x on the scripthash to create a new Account.
It seems unecessary at first but this constructor is being used by other libraries that tries to convert different kinds of input to an Address or ScriptHash.
=> feat: accept scriptHash with 0x prefix in Account constructor

docs/changelog/v5.md, package-lock.json, packages/neon-core/__tests__/u/basic/base64.ts, packages/neon-core/src/u/basic/base64.ts
Besides fixing the `utf82base64` method, I also added tests to the `utf82base64` and `base642utf8` methods
=> fix(u): fix utf82base64 conversion method

docs/changelog/v5.md, package-lock.json, packages/neon-core/package.json
There is already a [chore](https://github.com/CityOfZion/neon-js/pull/919) that is kinda doing this but since the docs and `types` on `package.json` should also be updated, I was instructed to create another PR with these other changes.
As to why this PR is changing only `crypto-js`, it's because it's the only dependency that is raising a severe vulnerability.
=> fix(deps): update crypto-js to 4.2.0

docs/changelog/v5.md
Fixing changelog version as a new feature was introduced so the minor version should be updated not the patch version.
=> fix(docs): update changelog

packages/neon-ledger/package.json
This was causing the released dist folder to only contain the index.js file.
=> fix(ledger): Export the dist folder correctly

packages/neon-core/src/wallet/Account.ts, packages/neon-core/tsconfig.json
Introduced a `validateKey` static method in the `Account` class that validates a string input and returns its type if valid, or `void`/`undefined` if invalid. This method streamlines validation by reducing the need for try/catch blocks and complex conditional checks, providing a clear and direct approach for assessing the health status of a string input.
=> Added Static Method to Account Class for Key Validation
